export const FILE_EXTENSIONS: Record<string, readonly string[]> = {
	IMAGE: ['jpg', 'jpeg', 'png', 'gif', 'bmp', 'webp', 'svg', 'ico', 'tiff', 'tif', 'avif'],
	VIDEO: ['mp4', 'mkv', 'avi', 'mov', 'wmv', 'flv', 'webm', 'm4v', 'mpeg', 'mpg'],
	AUDIO: ['mp3', 'wav', 'flac', 'aac', 'ogg', 'wma', 'm4a', 'opus'],
	CODE: [
		'js',
		'ts',
		'jsx',
		'tsx',
		'vue',
		'py',
		'java',
		'cpp',
		'c',
		'h',
		'rs',
		'go',
		'rb',
		'php',
		'swift',
		'kt',
		'cs',
		'html',
		'css',
		'scss',
		'sass',
		'less',
		'json',
		'xml',
		'yaml',
		'yml',
		'toml',
		'md',
		'sh',
		'bash',
		'ps1',
		'sql',
	],
	ARCHIVE: ['zip', 'rar', '7z', 'tar', 'gz', 'bz2', 'xz', 'iso'],
	TEXT: ['txt', 'log', 'ini', 'cfg', 'conf', 'env'],
};
